easy_admin:

    site_name: 'DinLanka'
    entities:
        User:
              label: "Manage Users"
              class: AppBundle\Entity\Fosuser
              list:
                  title: "Manage Users"
                  fields:
                        - id
                        - username
                        - email
                        - lastLogin
                        - { property: 'enabled' , type: 'boolean'}
              form:
                  title: "Manage Users"
                  fields:
                        - username
                        - email
                        - roles
                        - enabled
                        - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                        - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
        
        AirFreight_Orders:
              label: "Air Freight"
              class: AppBundle\Entity\AirFreight
              list:
                  title: "Air Freight"
                  actions: ['message']
              form:
                  title: "Air Freight"
              
                  
      

        DinLankaAirFreight_Orders:
              label: "DinLanka Air Freight"
              class: AppBundle\Entity\DinLankaAirFreight
              list:
                  title: "DinLanka Air Freight"
              form:
                  title: "DinLanka Air Freigh"

        SeaFreight_Orders:
              label: "Sea Freight"
              class: AppBundle\Entity\SeaFreight
              list:
                  title: "Sea Freight"
              form:
                  title: "Sea Freight"

        DinLankaSeaFreight_Orders:
              label: "DinLanka Sea Freight"
              class: AppBundle\Entity\DinLankaSeaFreight
              list:
                  title: "DinLanka Sea Freight"
              form:
                  title: "DinLanka Sea Freight"
              
        #Containers:
              #class: AppBundle\Entity\Container
              #list:
                  #title: "Container Details"
              #form:
                  #title: "Container Details"
        
        #UPBCargo:
              #class: AppBundle\Entity\upb
              #list:
                  #title: "UPB Cargo"
              #form:
                  #title: "UPB Cargo"

        #DinLankaUPBCargo:
              #class: AppBundle\Entity\DinLankaUPB
              #list:
                  #title: "DinLanka UPB Cargo"
              #form:
                  #title: "Container UPB Cargo"

    design:
        
        brand_color: 'rgba(241, 85, 27, 0.75)'

        menu:
            - {entity: 'User', icon: 'user' }
            - {entity: AirFreight_Orders, icon: 'plane'}
            - {entity: DinLankaAirFreight_Orders, icon: 'plane'}
            - {entity: SeaFreight_Orders, icon: 'ship'}
            - {entity: DinLankaSeaFreight_Orders, icon: 'ship'}
            #- {entity: Containers, icon: 'archive'}
            #- {entity: UPB, icon: 'archive'}
            #- {entity: DinlankaUpb, icon: 'archive'}

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'F j, Y h:i a'      


